title: Kevin Felix # your name (or website title) here
logo: "/images/image.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data-driven professional making data digestible. <br><br>
  Rubik's cube solver, cat lover, and fan of anything DC Comics!  <br><br>
  <a href="https://www.linkedin.com/in/kevinfelixleyva/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-tactile
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
